#!/usr/bin/env python3
"""
register_telemetry_hooks.py — idempotently wires the project Python hooks into
the LOCAL .claude/settings.json. Ships in the pack bundle; the bundle installer
auto-runs it so the usage-&-health lenses have data (opt out with --remove).

Scope: the 5 read-only TELEMETRY hooks PLUS the 2 ENFORCEMENT hooks
(memory_gap_hook, product_spec_critique_nudge). settings.json is ck-managed +
gitignored, so the bundle CANNOT ship a wired copy — wiring must happen on the
recipient, and this registrar is that single mechanism. The enforcement hooks
are WIRED-ALWAYS but config-gated: they no-op until product-spec-hooks.json sets
their key true (the installer's --memory-hook / --critique-hook flip that flag).
A blocking hook wired-but-disabled has the SAME observable effect as unwired.

Why a script instead of committing settings.json: settings.json is ck-managed
(regenerated by `ck init`, gitignored). Committing it would clobber ck content
and drift. This script ADDS ONLY the telemetry registrations and touches
nothing else — so telemetry survives a settings.json regen (just re-run it),
while ck-managed entries are left exactly as ck wrote them.

Interpreter: registered commands invoke the PYTHON hooks via the repo venv when
it exists (dev repo) and via system `python3` otherwise (recipient bundles have
no venv; the hooks are stdlib-only). Prior `node ...telemetry...cjs` registrations
are REPLACED/removed so we don't double-fire.

Usage:
  python3 register_telemetry_hooks.py            # register (default)
  python3 register_telemetry_hooks.py --remove   # unregister all telemetry hooks
  python3 register_telemetry_hooks.py --check    # report state, exit 1 if drift
  (--prune-spike: no-op; spike file deleted, kept for CLI compatibility)

Idempotent + upgrade-safe: re-running registers nothing new; a prior registration
of the same hook under a DIFFERENT interpreter/path (e.g. venv → system python3)
is reconciled to the current canonical command, never duplicated. Existence is
checked before every insert. Fail-LOUD by design (unlike the hooks themselves):
a wiring script should report problems, not swallow them.
"""

import json
import os
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or _SCRIPT_DIR / ".." / ".." / ".." / "..").resolve()
SETTINGS = REPO_ROOT / ".claude" / "settings.json"

def _interpreter() -> str:
    """Interpreter that will run the hooks. Prefer the repo venv when present (dev
    repo); fall back to system python3 — a recipient bundle has no venv, and every
    telemetry hook is stdlib-only so system python3 runs it fine."""
    venv = REPO_ROOT / ".claude" / "skills" / ".venv" / "bin" / "python3"
    return '"$CLAUDE_PROJECT_DIR"/.claude/skills/.venv/bin/python3' if venv.exists() else "python3"


PYTHON = _interpreter()


def _hook_cmd(file: str) -> str:
    return f'{PYTHON} "$CLAUDE_PROJECT_DIR"/.claude/hooks/{file}'


TRACK_SKILL = _hook_cmd("track_skill_invocation.py")
TRACK_SCRIPT = _hook_cmd("track_script_execution.py")
EMIT_SESSION = _hook_cmd("emit_session_summary.py")
MARK_BASH_START = _hook_cmd("mark_bash_start.py")
TRACK_SUBAGENT = _hook_cmd("track_subagent_outcome.py")
TRACK_ARTIFACT = _hook_cmd("track_artifact_edits.py")

# Enforcement hooks (wired-always, config-gated). memory_gap needs BOTH its Stop
# policy and its PostToolUse touched-flag writer (--post-tool-use); without the
# writer the Stop no-op guard never fires even when the hook is enabled.
MEMORY_GAP_STOP = _hook_cmd("memory_gap_hook.py")
MEMORY_GAP_POST = _hook_cmd("memory_gap_hook.py") + " --post-tool-use"
CRITIQUE_STOP = _hook_cmd("product_spec_critique_nudge.py")

# All current telemetry command strings (the read-only usage/health hooks).
TELEMETRY_CMDS: set[str] = {TRACK_SKILL, TRACK_SCRIPT, EMIT_SESSION, MARK_BASH_START, TRACK_SUBAGENT, TRACK_ARTIFACT}
# Every canonical command we own (telemetry + enforcement) — used by the reconcile
# pass so an enforcement entry is NOT mistaken for a stale telemetry form.
ALL_CMDS: set[str] = TELEMETRY_CMDS | {MEMORY_GAP_STOP, MEMORY_GAP_POST, CRITIQUE_STOP}

# Legacy node .cjs command substrings — these are replaced on register so we
# don't double-fire node+python.
_LEGACY_PATTERNS = [
    "track-skill-invocation.cjs",
    "track-script-execution.cjs",
    "emit-session-summary.cjs",
    "telemetry-spike.cjs",
]

# Our hook basenames — detect ANY prior registration of these hooks regardless of
# the interpreter/path prefix, so an upgrade that changes the interpreter
# (venv → system python3) reconciles the entry instead of duplicating it.
_HOOK_BASENAMES = (
    "track_skill_invocation.py", "track_script_execution.py", "emit_session_summary.py",
    "mark_bash_start.py", "track_subagent_outcome.py", "track_artifact_edits.py",
    "memory_gap_hook.py", "product_spec_critique_nudge.py",
)


def _references_our_hook(command: str) -> bool:
    return any(f"/.claude/hooks/{b}" in command for b in _HOOK_BASENAMES)

# Desired registrations. matcher=None means a matcher-less group.
# ship-both: skill hook on BOTH PreToolUse:Skill and UserPromptExpansion.
REGISTRATIONS = [
    {"event": "PreToolUse",          "matcher": "Skill", "commands": [TRACK_SKILL]},
    {"event": "UserPromptExpansion", "matcher": None,    "commands": [TRACK_SKILL]},
    {"event": "PreToolUse",          "matcher": "Bash",  "commands": [MARK_BASH_START]},
    {"event": "PostToolUse",         "matcher": "Bash",  "commands": [TRACK_SCRIPT]},
    {"event": "Stop",                "matcher": None,    "commands": [EMIT_SESSION]},
    {"event": "SubagentStop",        "matcher": None,    "commands": [TRACK_SUBAGENT]},
    # Enforcement hooks (wired-always; config default-false makes them no-op).
    # memory_gap's touched-flag writer rides PostToolUse:Edit|Write|MultiEdit.
    # track_artifact_edits records path-only events for spec artifacts (telemetry; fail-open).
    {"event": "PostToolUse",         "matcher": "Edit|Write|MultiEdit", "commands": [MEMORY_GAP_POST, TRACK_ARTIFACT]},
    {"event": "Stop",                "matcher": None,    "commands": [MEMORY_GAP_STOP, CRITIQUE_STOP]},
]


def load_settings() -> dict:
    # A recipient may have no settings.json yet (it's ck-managed + gitignored, never
    # shipped). Treat absence as an empty config so auto-registration can create it.
    if not SETTINGS.exists():
        return {}
    return json.loads(SETTINGS.read_text(encoding="utf-8"))


def _group_matches(group: dict, matcher) -> bool:
    if matcher is None:
        return "matcher" not in group or group.get("matcher") is None
    return group.get("matcher") == matcher


def _find_or_create_group(arr: list, matcher) -> dict:
    for g in arr:
        if _group_matches(g, matcher):
            if not isinstance(g.get("hooks"), list):
                g["hooks"] = []
            return g
    group = {"hooks": []} if matcher is None else {"matcher": matcher, "hooks": []}
    arr.append(group)
    return group


def _has_command(group: dict, command: str) -> bool:
    return any(h and h.get("command") == command for h in group.get("hooks", []))


def _is_legacy(command: str) -> bool:
    return any(pat in command for pat in _LEGACY_PATTERNS)


def register(settings: dict) -> int:
    hooks = settings.setdefault("hooks", {})
    added = 0
    # First: strip any legacy node .cjs telemetry registrations so we don't
    # double-fire node+python on the same event.
    _remove_matching(settings, _is_legacy)
    # Then reconcile any STALE-form telemetry entry (our hook basename, but a
    # different interpreter/path than the current canonical command) so a re-install
    # or upgrade that flips the interpreter can never leave the hook firing twice.
    _remove_matching(settings, lambda c: _references_our_hook(c) and c not in ALL_CMDS)
    for reg in REGISTRATIONS:
        arr = hooks.setdefault(reg["event"], [])
        group = _find_or_create_group(arr, reg["matcher"])
        for cmd in reg["commands"]:
            if not _has_command(group, cmd):
                group["hooks"].append({"type": "command", "command": cmd})
                added += 1
    return added


def _remove_matching(settings: dict, predicate) -> int:
    hooks = settings.get("hooks") or {}
    removed = 0
    for event in list(hooks.keys()):
        arr = hooks[event]
        if not isinstance(arr, list):
            continue
        for group in arr:
            if not group or not isinstance(group.get("hooks"), list):
                continue
            before = len(group["hooks"])
            group["hooks"] = [h for h in group["hooks"] if not (h and predicate(h.get("command", "")))]
            removed += before - len(group["hooks"])
        # Drop groups we emptied; drop the event key if no groups remain.
        hooks[event] = [g for g in arr if g and isinstance(g.get("hooks"), list) and g["hooks"]]
        if not hooks[event]:
            del hooks[event]
    return removed


def count_missing(settings: dict) -> int:
    hooks = settings.get("hooks") or {}
    missing = 0
    for reg in REGISTRATIONS:
        arr = hooks.get(reg["event"])
        group = next((g for g in arr if _group_matches(g, reg["matcher"])), None) if isinstance(arr, list) else None
        for cmd in reg["commands"]:
            if not group or not _has_command(group, cmd):
                missing += 1
    return missing


def write(settings: dict) -> None:
    SETTINGS.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    if "--remove" in argv:
        mode = "remove"
    elif "--prune-spike" in argv:
        mode = "prune-spike"
    elif "--check" in argv:
        mode = "check"
    else:
        mode = "register"

    try:
        settings = load_settings()
    except Exception as e:
        print(f"[register-telemetry] cannot read {SETTINGS}: {e}", file=sys.stderr)
        return 1

    if mode == "check":
        missing = count_missing(settings)
        if missing == 0:
            print("[register-telemetry] all telemetry hooks registered")
        else:
            print(f"[register-telemetry] {missing} registration(s) missing")
        return 0 if missing == 0 else 1

    if mode == "remove":
        # Strip our hooks under ANY interpreter/path form (not just the current
        # canonical), plus residual legacy node .cjs entries.
        n = _remove_matching(settings, _references_our_hook)
        n += _remove_matching(settings, _is_legacy)
        write(settings)
        print(f"[register-telemetry] removed {n} telemetry hook entr(ies)")
        return 0

    if mode == "prune-spike":
        # Spike file is deleted; this mode is a no-op but kept for CLI compat.
        # Also strip any residual legacy spike entries in case they remain.
        n = _remove_matching(settings, lambda cmd: "telemetry-spike" in cmd)
        if n:
            write(settings)
        print(f"[register-telemetry] pruned {n} telemetry-spike entr(ies)")
        return 0

    # register (default)
    added = register(settings)
    write(settings)
    suffix = "y" if added == 1 else "ies"
    print(f"[register-telemetry] registered ({added} new entr{suffix}); re-run is a no-op")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
