"""build_manifest_writer — assemble, validate, and atomic-write a manifest YAML file.

``write_manifest(answers, out_path, root)`` is the --write mode endpoint: it
assembles a manifest dict from the LLM-collected answers, validates it via
manifest_loader, and writes the result atomically (fsync + os.replace) so a
crash mid-write cannot leave a partial file.

The canonical key order and the YAML header comment are defined here; they
are consumed by build_manifest.py (the facade) for the round-trip test.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import yaml

import manifest_loader  # type: ignore[import-not-found]

CANONICAL_KEY_ORDER = (
    "schema_version", "version", "bundle_name",
    "skills", "agents", "hooks", "rules", "extra",
    "top_level", "defaults", "follow_shared",
)

HEADER_COMMENT = (
    "# Generated by cleanmatic:release build_manifest.py\n"
    "# Edit freely; this is the source-of-truth for pack/cli.py.\n"
    "# Schema: .claude/skills/release/references/manifest-spec.md\n"
)

CONFIRM_PROMPT_TEMPLATE = (
    "Ready to write .claude/pack.manifest.yaml with "
    "{n_skills} skills, {n_agents} agents, {n_rules} rules? [y/N]"
)

EXIT_OK = 0
EXIT_VALIDATION = 1
EXIT_COLLISION = 2


def _reorder(manifest: dict) -> dict:
    ordered: dict = {}
    for key in CANONICAL_KEY_ORDER:
        if key in manifest:
            ordered[key] = manifest[key]
    for key in manifest:
        if key not in ordered and not key.startswith("_"):
            ordered[key] = manifest[key]
    return ordered


def _assemble_manifest(answers: dict) -> dict:
    manifest: dict = {"schema_version": "1.0"}
    manifest["version"] = answers.get("version", "0.1.0")
    manifest["bundle_name"] = answers.get("bundle_name", "product-spec")
    for cat in ("skills", "agents", "hooks", "rules"):
        # Coerce only a genuine list/tuple. A malformed scalar (str/int from a
        # hand-authored stdin payload) is passed through UNCHANGED so
        # manifest_loader.validate() reports it as E010 — never list()-ed here
        # (which would char-split a string or raise TypeError on an int).
        val = answers.get(cat, [])
        manifest[cat] = list(val) if isinstance(val, (list, tuple)) else val
    extra = answers.get("extra", [])
    if isinstance(extra, str):
        extra = [s.strip() for s in extra.split(",") if s.strip()]
    manifest["extra"] = list(extra) if isinstance(extra, (list, tuple)) else extra
    manifest["top_level"] = {
        "include_readme": bool(answers.get("include_readme", False)),
        "include_claudemd": bool(answers.get("include_claudemd", False)),
        "include_settings": bool(answers.get("include_settings", False)),
        "include_ck_config": bool(answers.get("include_ck_config", False)),
    }
    defaults = answers.get("defaults") or {}
    if defaults:
        manifest["defaults"] = defaults
    manifest["follow_shared"] = bool(answers.get("follow_shared", False))
    return _reorder(manifest)


def _atomic_write_yaml(content: str, out_path: Path) -> None:
    """Atomic write via fsync + ``os.replace``. Cleanup tmp on failure."""
    tmp = out_path.parent / f".{out_path.name}.tmp"
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, out_path)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def write_manifest(answers: dict, out_path: Path, root: Path,
                   force: bool = False, allow_dev_version: bool = False) -> int:
    """Validate + atomic-write a manifest from an answers dict.

    Returns exit code (0/1/2).
    """
    manifest = _assemble_manifest(answers)

    out_resolved = out_path.resolve()
    root_resolved = root.resolve()
    try:
        out_resolved.relative_to(root_resolved)
    except ValueError:
        sys.stderr.write(f"refuse to write outside repo root: {out_resolved}\n")
        return EXIT_VALIDATION

    errors = manifest_loader.validate(manifest, root_resolved,
                                      allow_dev_version=allow_dev_version)
    if errors:
        for err in errors:
            sys.stderr.write(f"{err}\n")
        return EXIT_VALIDATION

    if out_path.exists() and not force:
        sys.stderr.write(f"manifest exists: {out_path} (use --force to overwrite)\n")
        return EXIT_COLLISION

    yaml_body = yaml.safe_dump(manifest, default_flow_style=False,
                               sort_keys=False, indent=2, width=80)
    content = HEADER_COMMENT + yaml_body
    _atomic_write_yaml(content, out_path)

    summary = {
        "ok": True,
        "path": str(out_path),
        "bytes": len(content.encode("utf-8")),
        "confirm_prompt": CONFIRM_PROMPT_TEMPLATE.format(
            n_skills=len(manifest.get("skills", [])),
            n_agents=len(manifest.get("agents", [])),
            n_rules=len(manifest.get("rules", [])),
        ),
    }
    json.dump(summary, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return EXIT_OK
