"""test_build_manifest — discover/list-questions/write round-trip."""

from __future__ import annotations

import yaml

import build_manifest
import manifest_loader


def test_discover_enumerates_skills(tmp_root):
    """discover finds sample-skill in tmp_root."""
    d = build_manifest.discover(tmp_root)
    assert "sample-skill" in d["available_skills"]
    assert "planner" in d["available_agents"]


def test_list_questions_has_four_batches(tmp_root):
    """question bank has 4 batches with canonical IDs."""
    d = build_manifest.discover(tmp_root)
    qs = build_manifest.list_questions(d)
    ids = [b["id"] for b in qs["batches"]]
    assert ids == ["version-and-name", "categories", "top-level", "extras-and-shared"]
    assert qs["schema_version"] == "1.0"


def test_write_round_trip(tmp_root):
    """discover -> list-questions -> answers -> write -> load -> equal."""
    answers = {
        "version": "0.2.0",
        "bundle_name": "test-pack",
        "skills": ["sample-skill"],
        "agents": ["planner"],
        "hooks": [],
        "rules": ["primary-workflow.md"],
        "extra": [],
        "include_readme": False,
        "include_claudemd": False,
        "include_settings": False,
        "include_ck_config": False,
        "follow_shared": False,
    }
    out_path = tmp_root / ".claude" / "pack.manifest.yaml"
    rc = build_manifest.write_manifest(answers, out_path, tmp_root, force=False)
    assert rc == 0
    assert out_path.is_file()
    body = out_path.read_text(encoding="utf-8")
    assert body.startswith("# Generated by cleanmatic:claude-pack")
    loaded = manifest_loader.load(out_path)
    assert loaded["version"] == "0.2.0"
    assert loaded["skills"] == ["sample-skill"]


def test_write_refuses_existing_without_force(tmp_root):
    out_path = tmp_root / ".claude" / "pack.manifest.yaml"
    out_path.write_text("# existing\n", encoding="utf-8")
    answers = {"version": "1.0.0", "skills": ["sample-skill"]}
    rc = build_manifest.write_manifest(answers, out_path, tmp_root, force=False)
    assert rc == 2  # EXIT_COLLISION


def test_write_overwrite_with_force(tmp_root):
    out_path = tmp_root / ".claude" / "pack.manifest.yaml"
    out_path.write_text("# existing\n", encoding="utf-8")
    answers = {"version": "1.0.0", "skills": ["sample-skill"]}
    rc = build_manifest.write_manifest(answers, out_path, tmp_root, force=True)
    assert rc == 0
    body = out_path.read_text(encoding="utf-8")
    assert "Generated by cleanmatic:claude-pack" in body


def test_write_invalid_version_no_partial_file(tmp_root):
    """invalid version -> exit 1 + no file written."""
    out_path = tmp_root / ".claude" / "pack.manifest.yaml"
    assert not out_path.exists()
    rc = build_manifest.write_manifest(
        {"version": "not-semver"}, out_path, tmp_root, force=False,
    )
    assert rc == 1  # EXIT_VALIDATION
    assert not out_path.exists()


def test_write_byte_identical_for_same_answers(tmp_root):
    answers = {
        "version": "0.2.0", "bundle_name": "x",
        "skills": ["sample-skill"], "agents": [], "hooks": [],
        "rules": [], "extra": [],
        "include_readme": False, "include_claudemd": False,
        "include_settings": False, "include_ck_config": False,
        "follow_shared": False,
    }
    p1 = tmp_root / "a.yaml"
    p2 = tmp_root / "b.yaml"
    assert build_manifest.write_manifest(answers, p1, tmp_root) == 0
    assert build_manifest.write_manifest(answers, p2, tmp_root) == 0
    assert p1.read_bytes() == p2.read_bytes()


def test_write_refuses_outside_repo_root(tmp_root, tmp_path):
    outside = tmp_path.parent / "outside-pack.yaml"
    rc = build_manifest.write_manifest(
        {"version": "1.0.0", "skills": ["sample-skill"]},
        outside, tmp_root, force=False,
    )
    assert rc == 1


def test_canonical_key_order(tmp_root):
    answers = {
        "version": "0.1.0", "bundle_name": "p",
        "skills": ["sample-skill"], "agents": [], "hooks": [],
        "rules": [], "extra": [],
        "include_readme": False, "include_claudemd": False,
        "include_settings": False, "include_ck_config": False,
        "follow_shared": False,
    }
    p = tmp_root / "pack.yaml"
    build_manifest.write_manifest(answers, p, tmp_root)
    text = p.read_text(encoding="utf-8")
    yaml_body = "\n".join(l for l in text.splitlines() if not l.startswith("#"))
    loaded = yaml.safe_load(yaml_body)
    seen_keys = list(loaded.keys())
    canonical = list(build_manifest.CANONICAL_KEY_ORDER)
    seen_positions = [canonical.index(k) for k in seen_keys if k in canonical]
    assert seen_positions == sorted(seen_positions), \
        f"keys out of canonical order: {seen_keys}"


# ---------------------------------------------------------------------------
# Cycle-10 regression tests
# ---------------------------------------------------------------------------

def test_write_non_dict_null_returns_validation_error(tmp_root, monkeypatch):
    """--write with JSON null on stdin must return EXIT_VALIDATION, not AttributeError."""
    import io
    out_path = tmp_root / ".claude" / "c10-null.yaml"
    monkeypatch.setattr("sys.stdin", io.StringIO("null"))
    # main() reads from sys.stdin when --write is used
    rc = build_manifest.main([
        "--write", "--root", str(tmp_root), "--out", str(out_path),
        "--allow-dev-version",
    ])
    assert rc == build_manifest.EXIT_VALIDATION, \
        f"expected EXIT_VALIDATION (1) for null stdin, got {rc}"
    assert not out_path.exists(), "no file should be written for invalid stdin"


def test_write_non_dict_list_returns_validation_error(tmp_root, monkeypatch):
    """--write with JSON array on stdin must return EXIT_VALIDATION, not AttributeError."""
    import io
    out_path = tmp_root / ".claude" / "c10-list.yaml"
    monkeypatch.setattr("sys.stdin", io.StringIO('["skill-a", "skill-b"]'))
    rc = build_manifest.main([
        "--write", "--root", str(tmp_root), "--out", str(out_path),
        "--allow-dev-version",
    ])
    assert rc == build_manifest.EXIT_VALIDATION, \
        f"expected EXIT_VALIDATION (1) for list stdin, got {rc}"
    assert not out_path.exists()


def test_write_non_dict_number_returns_validation_error(tmp_root, monkeypatch):
    """--write with a plain number on stdin must return EXIT_VALIDATION."""
    import io
    out_path = tmp_root / ".claude" / "c10-num.yaml"
    monkeypatch.setattr("sys.stdin", io.StringIO("42"))
    rc = build_manifest.main([
        "--write", "--root", str(tmp_root), "--out", str(out_path),
        "--allow-dev-version",
    ])
    assert rc == build_manifest.EXIT_VALIDATION
    assert not out_path.exists()
