#!/usr/bin/env python3
"""Build the Product Spec Harness showcase from a single source of truth.

Source of truth (hand-authored):
  partials/hub.html, partials/<skill>.html   — page content
  partials/_footer.html                        — shared footer ({ROOT} = repo-root prefix)
  assets/showcase.css, assets/showcase.js      — shared styles + behavior

Outputs (generated — DO NOT hand-edit):
  index.html                                   — multipage hub
  skills/<skill>.html                          — multipage per-skill pages (shared <link>/<script>)
  product-spec-showcase.html                   — ONE portable file (CSS+JS inlined, hash-router)

Multipage nav uses real page links; the portable file wraps every page in a
[data-route] panel and the router in showcase.js switches them on hashchange, so
both targets share identical content and UX. Stdlib only — run: python3 build.py
"""
import html
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
PARTIALS = HERE / "partials"
ASSETS = HERE / "assets"
ARTDIR = HERE / "artifacts"

# key, nav label (en), nav label (vi), partial file, <title>, accent css-var
PAGES = [
    ("hub",          "Overview",     "Tổng quan",  "hub.html",          "Product Spec Harness — Interactive Showcase", "var(--spec)"),
    ("product-spec", "product-spec", "product-spec","product-spec.html", "product-spec — Product Spec Harness",         "var(--spec)"),
    ("critique",     "critique",     "critique",   "critique.html",     "critique — Product Spec Harness",             "var(--crit)"),
    ("release",      "release",      "release",    "release.html",      "release — Product Spec Harness",              "var(--rel)"),
    ("telemetry",    "telemetry",    "telemetry",  "telemetry.html",    "telemetry — Product Spec Harness",            "var(--tel)"),
]
DESC = ("An interactive, standalone tour of the Product Spec Harness: four Claude Code "
        "skills that define, validate, critique, ship and observe product specs.")
GEN_BANNER = "<!-- GENERATED by build.py — edit showcase/partials/ + assets/, never this file -->"
CHROME = ('<div class="glow g1"></div><div class="glow g2"></div><div class="glow g3"></div>\n'
          '<canvas id="net"></canvas>')


def read(p):
    fp = PARTIALS / p
    return fp.read_text(encoding="utf-8") if fp.exists() else f"<!-- missing partial: {p} -->"


def _art(name):
    return (ARTDIR / name).read_text(encoding="utf-8")


def _pre(name):
    """Real captured stdout, escaped, in a <pre> block."""
    return "<pre>" + html.escape(_art(name), quote=False) + "</pre>"


# placeholder token -> artifact file rendered as a <pre> terminal block
_PRE_TOKENS = {
    "<!--VIZ_TREE-->": "acme-viz-tree.txt",
    "<!--RELEASE_DRYRUN-->": "release-dryrun.txt",
    "<!--TEL_ASCII-->": "telemetry-usage.ascii.txt",
    "<!--TEL_MD-->": "telemetry-usage.md.txt",
    "<!--TEL_MERMAID-->": "telemetry-usage.mermaid.txt",
    "<!--TEL_JSON-->": "telemetry-usage.json.txt",
}


def inject(text, mode, art_rel):
    """Replace artifact placeholders in a partial with the real captured output.
    Artifacts are the single source of truth — never pasted into partials."""
    for tok, fn in _PRE_TOKENS.items():
        if tok in text:
            text = text.replace(tok, _pre(fn))
    if "<!--FINDING_DATA-->" in text:
        raw = _art("acme-critique-finding.json").replace("</", "<\\/")  # no script-breakout
        text = text.replace(
            "<!--FINDING_DATA-->",
            '<script type="application/json" id="finding-data">' + raw + "</script>")
    if "<!--BOARD_EMBED-->" in text:
        if mode == "single":   # truly standalone: inline the board via srcdoc
            sd = _art("acme-viz-board.html").replace("&", "&amp;").replace('"', "&quot;")
            embed = ('<iframe class="board-frame" loading="lazy" '
                     'title="Acme Shop — board view" srcdoc="' + sd + '"></iframe>')
        else:                  # multipage: reference the artifact file
            embed = ('<iframe class="board-frame" loading="lazy" title="Acme Shop — board view" '
                     'src="' + art_rel + 'artifacts/acme-viz-board.html"></iframe>')
        text = text.replace("<!--BOARD_EMBED-->", embed)
    return text


def nav(active, mode, nav_rel):
    """Top nav. mode='multi' → real page links + baked .active; mode='single' → #hash links."""
    out = []
    for key, en, vi, _f, _t, _ac in PAGES:
        if mode == "single":
            href = "#" + key
        elif key == "hub":
            href = nav_rel + "index.html"
        else:
            href = nav_rel + "skills/" + key + ".html"
        cls = " active" if (mode == "multi" and key == active) else ""
        out.append(f'<a href="{href}" class="navlink{cls}" data-nav="{key}">'
                   f'<span class="en">{en}</span><span class="vi">{vi}</span></a>')
    home = ("#hub" if mode == "single" else nav_rel + "index.html")
    return (
        '<nav>\n  <div class="nav-in">\n'
        f'    <a href="{home}" class="brand"><span class="dot"></span>'
        '<span>Product&nbsp;Spec&nbsp;Harness</span></a>\n'
        '    <div class="nav-links">\n      ' + "\n      ".join(out) + "\n    </div>\n"
        '    <div class="langtoggle" role="group" aria-label="language">\n'
        '      <button id="btn-en" class="active" onclick="setLang(\'en\')">EN</button>\n'
        '      <button id="btn-vi" onclick="setLang(\'vi\')">VI</button>\n'
        '    </div>\n  </div>\n</nav>'
    )


def crumb(key, nav_rel):
    label = next(p[1] for p in PAGES if p[0] == key)
    home = nav_rel + "index.html"
    return (f'<div class="crumb"><a href="{home}"><span class="en">Home</span>'
            f'<span class="vi">Trang chủ</span></a> <span class="sep">›</span> '
            f'<span class="cur">{label}</span></div>')


def skill_nav(key, mode, nav_rel):
    """Generated prev · hub · next footer nav for a skill page (DRY: order lives in PAGES)."""
    idx = next(i for i, p in enumerate(PAGES) if p[0] == key)
    ac = PAGES[idx][5]

    def href(k):
        if mode == "single":
            return "#" + k
        if k == "hub":
            return nav_rel + "index.html"
        return nav_rel + "skills/" + k + ".html"

    prev = PAGES[idx - 1]                       # idx>=1 for skills; prev may be hub
    nxt = PAGES[idx + 1] if idx + 1 < len(PAGES) else None
    parts = [f'<div class="skill-nav" style="--ac:{ac}">']
    parts.append(f'<a class="pv" href="{href(prev[0])}"><span class="k">← '
                 '<span class="en">Prev</span><span class="vi">Trước</span></span>'
                 f'<span class="v">{prev[1]}</span></a>')
    parts.append(f'<a class="hb" href="{href("hub")}"><span class="k">'
                 '<span class="en">Overview</span><span class="vi">Tổng quan</span></span>'
                 '<span class="v">▦</span></a>')
    if nxt:
        parts.append(f'<a class="nx" href="{href(nxt[0])}"><span class="k">'
                     '<span class="en">Next</span><span class="vi">Sau</span> →</span>'
                     f'<span class="v">{nxt[1]}</span></a>')
    else:                                        # last skill: keep layout balanced
        parts.append('<span class="nx" style="flex:1"></span>')
    parts.append("</div>")
    return "".join(parts)


def head(title, head_inject):
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        '<meta charset="UTF-8" />\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        f"<title>{title}</title>\n"
        f'<meta name="description" content="{DESC}" />\n'
        f"{head_inject}\n</head>\n"
    )


def shell(title, head_inject, nav_html, breadcrumb, main, footer, script_inject):
    bc = (breadcrumb + "\n") if breadcrumb else ""
    return (
        head(title, head_inject)
        + '<body class="lang-en">\n' + GEN_BANNER + "\n"
        + CHROME + "\n"
        + nav_html + "\n"
        + bc
        + main + "\n"
        + footer + "\n"
        + script_inject + "\n"
        + "</body>\n</html>\n"
    )


def build():
    css = (ASSETS / "showcase.css").read_text(encoding="utf-8")
    js = (ASSETS / "showcase.js").read_text(encoding="utf-8")
    footer_tpl = read("_footer.html")
    written = []

    # ---------- multipage ----------
    # index.html (hub): asset_rel='' root_rel='../' nav_rel=''
    link = '<link rel="stylesheet" href="assets/showcase.css" />'
    script = '<script src="assets/showcase.js"></script>'
    footer = footer_tpl.replace("{ROOT}", "../")
    out = shell(PAGES[0][4], link, nav("hub", "multi", ""), "",
                inject(read("hub.html"), "multi", ""), footer, script)
    (HERE / "index.html").write_text(out, encoding="utf-8")
    written.append("index.html")

    # skills/<k>.html: asset_rel='../' root_rel='../../' nav_rel='../'
    link2 = '<link rel="stylesheet" href="../assets/showcase.css" />'
    script2 = '<script src="../assets/showcase.js"></script>'
    footer2 = footer_tpl.replace("{ROOT}", "../../")
    for key, en, vi, pf, title, ac in PAGES[1:]:
        main = inject(read(pf), "multi", "../") + "\n<div class=\"wrap\">" + skill_nav(key, "multi", "../") + "</div>"
        out = shell(title, link2, nav(key, "multi", "../"), crumb(key, "../"), main, footer2, script2)
        (HERE / "skills" / (key + ".html")).write_text(out, encoding="utf-8")
        written.append(f"skills/{key}.html")

    # ---------- portable single file ----------
    # Emitted at showcase/ root (NOT dist/ or build/ — those are gitignored AND dropped by the
    # release safety filter, which would make the portable artifact invisible). root_rel='../'.
    style_inline = "<style>\n" + css + "\n</style>"
    script_inline = "<script>\n" + js + "\n</script>"
    footer_single = footer_tpl.replace("{ROOT}", "../")
    panels = []
    for key, en, vi, pf, title, ac in PAGES:
        body = inject(read(pf), "single", "")
        if key != "hub":
            body += "\n<div class=\"wrap\">" + skill_nav(key, "single", "") + "</div>"
        panels.append(f'<div class="route" data-route="{key}">\n{body}\n</div>')
    main_single = "\n".join(panels)
    out = shell(PAGES[0][4], style_inline, nav("hub", "single", ""), "", main_single,
                footer_single, script_inline)
    (HERE / "product-spec-showcase.html").write_text(out, encoding="utf-8")
    written.append("product-spec-showcase.html")

    return written


if __name__ == "__main__":
    for w in build():
        print("wrote", w)
