#!/usr/bin/env python3
"""
register_telemetry_hooks.py — idempotently wires the telemetry hooks into the
LOCAL .claude/settings.json. CM-local dev tooling (NOT shipped in the pack
bundle).

Why a script instead of committing settings.json: settings.json is ck-managed
(regenerated by `ck init`, gitignored). Committing it would clobber ck content
and drift. This script ADDS ONLY the telemetry registrations and touches
nothing else — so telemetry survives a settings.json regen (just re-run it),
while ck-managed entries are left exactly as ck wrote them.

CRITICAL: registered commands invoke the PYTHON hooks via the venv interpreter
  .claude/skills/.venv/bin/python3 .claude/hooks/<hook>.py
NOT the old `node ...cjs` form. If prior `node ...telemetry...cjs` registrations
exist in settings.json they are REPLACED/removed so we don't double-fire.

Usage:
  python3 register_telemetry_hooks.py            # register (default)
  python3 register_telemetry_hooks.py --remove   # unregister all telemetry hooks
  python3 register_telemetry_hooks.py --check    # report state, exit 1 if drift
  (--prune-spike: no-op; spike file deleted, kept for CLI compatibility)

Idempotent: re-running registers nothing new. Dedup is by exact command string.
Fail-LOUD by design (unlike the hooks themselves): a wiring script should
report problems, not swallow them.
"""

import json
import os
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or _SCRIPT_DIR / ".." / ".." / ".." / "..").resolve()
SETTINGS = REPO_ROOT / ".claude" / "settings.json"

VENV_PY = '\"$CLAUDE_PROJECT_DIR\"/.claude/skills/.venv/bin/python3'


def _hook_cmd(file: str) -> str:
    return f'{VENV_PY} "$CLAUDE_PROJECT_DIR"/.claude/hooks/{file}'


TRACK_SKILL = _hook_cmd("track_skill_invocation.py")
TRACK_SCRIPT = _hook_cmd("track_script_execution.py")
EMIT_SESSION = _hook_cmd("emit_session_summary.py")

# All current telemetry command strings (used to identify our entries).
TELEMETRY_CMDS: set[str] = {TRACK_SKILL, TRACK_SCRIPT, EMIT_SESSION}

# Legacy node .cjs command substrings — these are replaced on register so we
# don't double-fire node+python.
_LEGACY_PATTERNS = [
    "track-skill-invocation.cjs",
    "track-script-execution.cjs",
    "emit-session-summary.cjs",
    "telemetry-spike.cjs",
]

# Desired registrations. matcher=None means a matcher-less group.
# ship-both: skill hook on BOTH PreToolUse:Skill and UserPromptExpansion.
REGISTRATIONS = [
    {"event": "PreToolUse",          "matcher": "Skill", "commands": [TRACK_SKILL]},
    {"event": "UserPromptExpansion", "matcher": None,    "commands": [TRACK_SKILL]},
    {"event": "PostToolUse",         "matcher": "Bash",  "commands": [TRACK_SCRIPT]},
    {"event": "Stop",                "matcher": None,    "commands": [EMIT_SESSION]},
]


def load_settings() -> dict:
    return json.loads(SETTINGS.read_text(encoding="utf-8"))


def _group_matches(group: dict, matcher) -> bool:
    if matcher is None:
        return "matcher" not in group or group.get("matcher") is None
    return group.get("matcher") == matcher


def _find_or_create_group(arr: list, matcher) -> dict:
    for g in arr:
        if _group_matches(g, matcher):
            if not isinstance(g.get("hooks"), list):
                g["hooks"] = []
            return g
    group = {"hooks": []} if matcher is None else {"matcher": matcher, "hooks": []}
    arr.append(group)
    return group


def _has_command(group: dict, command: str) -> bool:
    return any(h and h.get("command") == command for h in group.get("hooks", []))


def _is_legacy(command: str) -> bool:
    return any(pat in command for pat in _LEGACY_PATTERNS)


def register(settings: dict) -> int:
    hooks = settings.setdefault("hooks", {})
    added = 0
    # First: strip any legacy node .cjs telemetry registrations so we don't
    # double-fire node+python on the same event.
    _remove_matching(settings, _is_legacy)
    for reg in REGISTRATIONS:
        arr = hooks.setdefault(reg["event"], [])
        group = _find_or_create_group(arr, reg["matcher"])
        for cmd in reg["commands"]:
            if not _has_command(group, cmd):
                group["hooks"].append({"type": "command", "command": cmd})
                added += 1
    return added


def _remove_matching(settings: dict, predicate) -> int:
    hooks = settings.get("hooks") or {}
    removed = 0
    for event in list(hooks.keys()):
        arr = hooks[event]
        if not isinstance(arr, list):
            continue
        for group in arr:
            if not group or not isinstance(group.get("hooks"), list):
                continue
            before = len(group["hooks"])
            group["hooks"] = [h for h in group["hooks"] if not (h and predicate(h.get("command", "")))]
            removed += before - len(group["hooks"])
        # Drop groups we emptied; drop the event key if no groups remain.
        hooks[event] = [g for g in arr if g and isinstance(g.get("hooks"), list) and g["hooks"]]
        if not hooks[event]:
            del hooks[event]
    return removed


def remove_commands(settings: dict, cmd_set: set) -> int:
    return _remove_matching(settings, lambda cmd: cmd in cmd_set)


def count_missing(settings: dict) -> int:
    hooks = settings.get("hooks") or {}
    missing = 0
    for reg in REGISTRATIONS:
        arr = hooks.get(reg["event"])
        group = next((g for g in arr if _group_matches(g, reg["matcher"])), None) if isinstance(arr, list) else None
        for cmd in reg["commands"]:
            if not group or not _has_command(group, cmd):
                missing += 1
    return missing


def write(settings: dict) -> None:
    SETTINGS.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")


def main(argv: list[str]) -> int:
    if "--remove" in argv:
        mode = "remove"
    elif "--prune-spike" in argv:
        mode = "prune-spike"
    elif "--check" in argv:
        mode = "check"
    else:
        mode = "register"

    try:
        settings = load_settings()
    except Exception as e:
        print(f"[register-telemetry] cannot read {SETTINGS}: {e}", file=sys.stderr)
        return 1

    if mode == "check":
        missing = count_missing(settings)
        if missing == 0:
            print("[register-telemetry] all telemetry hooks registered")
        else:
            print(f"[register-telemetry] {missing} registration(s) missing")
        return 0 if missing == 0 else 1

    if mode == "remove":
        n = remove_commands(settings, TELEMETRY_CMDS)
        # Also strip any residual legacy node .cjs entries
        n += _remove_matching(settings, _is_legacy)
        write(settings)
        print(f"[register-telemetry] removed {n} telemetry hook entr(ies)")
        return 0

    if mode == "prune-spike":
        # Spike file is deleted; this mode is a no-op but kept for CLI compat.
        # Also strip any residual legacy spike entries in case they remain.
        n = _remove_matching(settings, lambda cmd: "telemetry-spike" in cmd)
        if n:
            write(settings)
        print(f"[register-telemetry] pruned {n} telemetry-spike entr(ies)")
        return 0

    # register (default)
    added = register(settings)
    write(settings)
    suffix = "y" if added == 1 else "ies"
    print(f"[register-telemetry] registered ({added} new entr{suffix}); re-run is a no-op")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
