"""build_manifest — interactive manifest builder for cleanmatic:claude-pack.

Three modes (mutually exclusive):
- ``--discover`` — scan ``.claude/`` and emit a JSON catalog.
- ``--list-questions`` — emit the canonical question bank as JSON for the LLM
  to walk via ``AskUserQuestion``.
- ``--write`` — read answers JSON from stdin, validate via ``manifest_loader``,
  atomic-write to ``.claude/pack.manifest.yaml``.

Python NEVER calls ``AskUserQuestion`` — the LLM is the UI layer.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

import manifest_loader  # type: ignore[import-not-found]

CANONICAL_KEY_ORDER = (
    "schema_version", "version", "bundle_name",
    "skills", "agents", "hooks", "rules", "extra",
    "top_level", "defaults", "follow_shared",
)

HEADER_COMMENT = (
    "# Generated by cleanmatic:claude-pack build_manifest.py\n"
    "# Edit freely; this is the source-of-truth for pack/cli.py.\n"
    "# Schema: .claude/skills/claude-pack/references/manifest-spec.md\n"
)

CONFIRM_PROMPT_TEMPLATE = (
    "Ready to write .claude/pack.manifest.yaml with "
    "{n_skills} skills, {n_agents} agents, {n_rules} rules? [y/N]"
)

EXIT_OK = 0
EXIT_VALIDATION = 1
EXIT_COLLISION = 2


# ---------------------------------------------------------------------------
# discover
# ---------------------------------------------------------------------------

def discover(root: Path) -> dict:
    """Enumerate available items under ``.claude/``."""
    claude = root / ".claude"
    skills_dir = claude / "skills"
    agents_dir = claude / "agents"
    rules_dir = claude / "rules"
    hooks_dir = claude / "hooks"

    available_skills: list[str] = []
    if skills_dir.is_dir():
        for entry in sorted(skills_dir.iterdir()):
            if (entry.is_dir() and entry.name not in {"_shared", ".venv"}
                    and (entry / "SKILL.md").is_file()):
                available_skills.append(entry.name)

    def _basenames(directory: Path, suffix: str) -> list[str]:
        """Return stem names that are unambiguous (1:1 stem → file).

        Stems that map to more than one file (same stem, different directories)
        are excluded because ``manifest_loader._resolve_extension`` would be
        ambiguous on them — including them as options would produce MANIFEST_E071/
        E072 collisions at validate time.
        """
        if not directory.is_dir():
            return []
        stem_to_paths: dict[str, list[str]] = {}
        for p in directory.rglob(f"*{suffix}"):
            if p.is_file():
                stem_to_paths.setdefault(p.stem, []).append(str(p))
        # Only offer stems that have exactly one backing file.
        return sorted(stem for stem, paths in stem_to_paths.items() if len(paths) == 1)

    def _filenames(directory: Path) -> list[str]:
        """Return relative posix paths for all files under directory (recursive).

        Hooks may live in subdirectories; using rglob here aligns with
        ``manifest_loader.match_hooks`` which also recurses, so offered options
        match what validates and ships.
        """
        if not directory.is_dir():
            return []
        base = directory
        return sorted(
            p.relative_to(base).as_posix()
            for p in directory.rglob("*")
            if p.is_file()
        )

    return {
        "available_skills": available_skills,
        "available_agents": _basenames(agents_dir, ".md"),
        "available_hooks": _filenames(hooks_dir),
        "available_rules": _basenames(rules_dir, ".md"),
        "has_readme": (root / "README.md").is_file(),
        "has_claudemd": (root / "CLAUDE.md").is_file(),
        "has_settings": (claude / "settings.json").is_file(),
        "has_ck_config": (claude / ".ck.json").is_file(),
    }


# ---------------------------------------------------------------------------
# list_questions
# ---------------------------------------------------------------------------

def _option_list(values: list[str]) -> list[dict]:
    return [{"label": v, "value": v} for v in values]


def list_questions(discovery: dict, lang: str = "en") -> dict:
    """Return canonical question bank as a 4-batch JSON tree."""
    return {
        "schema_version": "1.0",
        "lang": lang,
        "batches": [
            {
                "id": "version-and-name",
                "questions": [
                    {"id": "version", "header": "Version", "type": "text",
                     "question": "Bundle version (SemVer 2.0.0, e.g. 1.0.0)?",
                     "default": "0.1.0", "validate": "semver"},
                    {"id": "bundle_name", "header": "Bundle name", "type": "text",
                     "question": "Bundle filename stem?",
                     "default": "claude-pack"},
                ],
            },
            {
                "id": "categories",
                "questions": [
                    {"id": "skills", "header": "Skills", "type": "multi-select",
                     "question": "Which skills to include?",
                     "options": _option_list(discovery["available_skills"])},
                    {"id": "agents", "header": "Agents", "type": "multi-select",
                     "question": "Which agents to include?",
                     "options": _option_list(discovery["available_agents"])},
                    {"id": "hooks", "header": "Hooks", "type": "multi-select",
                     "question": "Which hooks to include?",
                     "options": _option_list(discovery["available_hooks"])},
                    {"id": "rules", "header": "Rules", "type": "multi-select",
                     "question": "Which rules to include?",
                     "options": _option_list(discovery["available_rules"])},
                ],
            },
            {
                "id": "top-level",
                "questions": [
                    {"id": "include_readme", "header": "README", "type": "bool",
                     "question": "Include repo-root README.md?",
                     "default": False, "available": discovery["has_readme"]},
                    {"id": "include_claudemd", "header": "CLAUDE.md", "type": "bool",
                     "question": "Include repo-root CLAUDE.md?",
                     "default": False, "available": discovery["has_claudemd"]},
                    {"id": "include_settings", "header": "settings.json", "type": "bool",
                     "question": "Include .claude/settings.json? (opt-in only)",
                     "default": False, "available": discovery["has_settings"]},
                    {"id": "include_ck_config", "header": ".ck.json", "type": "bool",
                     "question": "Include .claude/.ck.json? (opt-in only)",
                     "default": False, "available": discovery["has_ck_config"]},
                ],
            },
            {
                "id": "extras-and-shared",
                "questions": [
                    {"id": "extra", "header": "Extra paths", "type": "text-list",
                     "question": "Extra repo-relative paths (comma-separated). "
                                 "NO absolute, NO `..`.",
                     "default": []},
                    {"id": "follow_shared", "header": "_shared/", "type": "bool",
                     "question": "Auto-include _shared/<name> refs from packed skills? "
                                 "(default false = warn-only)",
                     "default": False},
                ],
            },
        ],
    }


# ---------------------------------------------------------------------------
# write_manifest
# ---------------------------------------------------------------------------

def _reorder(manifest: dict) -> dict:
    ordered: dict = {}
    for key in CANONICAL_KEY_ORDER:
        if key in manifest:
            ordered[key] = manifest[key]
    for key in manifest:
        if key not in ordered and not key.startswith("_"):
            ordered[key] = manifest[key]
    return ordered


def _assemble_manifest(answers: dict) -> dict:
    manifest: dict = {"schema_version": "1.0"}
    manifest["version"] = answers.get("version", "0.1.0")
    manifest["bundle_name"] = answers.get("bundle_name", "claude-pack")
    for cat in ("skills", "agents", "hooks", "rules"):
        # Coerce only a genuine list/tuple. A malformed scalar (str/int from a
        # hand-authored stdin payload) is passed through UNCHANGED so
        # manifest_loader.validate() reports it as E010 — never list()-ed here
        # (which would char-split a string or raise TypeError on an int).
        val = answers.get(cat, [])
        manifest[cat] = list(val) if isinstance(val, (list, tuple)) else val
    extra = answers.get("extra", [])
    if isinstance(extra, str):
        extra = [s.strip() for s in extra.split(",") if s.strip()]
    manifest["extra"] = list(extra) if isinstance(extra, (list, tuple)) else extra
    manifest["top_level"] = {
        "include_readme": bool(answers.get("include_readme", False)),
        "include_claudemd": bool(answers.get("include_claudemd", False)),
        "include_settings": bool(answers.get("include_settings", False)),
        "include_ck_config": bool(answers.get("include_ck_config", False)),
    }
    defaults = answers.get("defaults") or {}
    if defaults:
        manifest["defaults"] = defaults
    manifest["follow_shared"] = bool(answers.get("follow_shared", False))
    return _reorder(manifest)


def _atomic_write_yaml(content: str, out_path: Path) -> None:
    """Atomic write via fsync + ``os.replace``. Cleanup tmp on failure."""
    tmp = out_path.parent / f".{out_path.name}.tmp"
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, out_path)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def write_manifest(answers: dict, out_path: Path, root: Path,
                   force: bool = False, allow_dev_version: bool = False) -> int:
    """Validate + atomic-write a manifest from an answers dict.

    Returns exit code (0/1/2).
    """
    manifest = _assemble_manifest(answers)

    out_resolved = out_path.resolve()
    root_resolved = root.resolve()
    try:
        out_resolved.relative_to(root_resolved)
    except ValueError:
        sys.stderr.write(f"refuse to write outside repo root: {out_resolved}\n")
        return EXIT_VALIDATION

    errors = manifest_loader.validate(manifest, root_resolved,
                                      allow_dev_version=allow_dev_version)
    if errors:
        for err in errors:
            sys.stderr.write(f"{err}\n")
        return EXIT_VALIDATION

    if out_path.exists() and not force:
        sys.stderr.write(f"manifest exists: {out_path} (use --force to overwrite)\n")
        return EXIT_COLLISION

    yaml_body = yaml.safe_dump(manifest, default_flow_style=False,
                               sort_keys=False, indent=2, width=80)
    content = HEADER_COMMENT + yaml_body
    _atomic_write_yaml(content, out_path)

    summary = {
        "ok": True,
        "path": str(out_path),
        "bytes": len(content.encode("utf-8")),
        "confirm_prompt": CONFIRM_PROMPT_TEMPLATE.format(
            n_skills=len(manifest.get("skills", [])),
            n_agents=len(manifest.get("agents", [])),
            n_rules=len(manifest.get("rules", [])),
        ),
    }
    json.dump(summary, sys.stdout, indent=2)
    sys.stdout.write("\n")
    return EXIT_OK


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="build_manifest",
                                description="claude-pack interactive manifest builder")
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--discover", action="store_true")
    mode.add_argument("--list-questions", dest="list_questions", action="store_true")
    mode.add_argument("--write", action="store_true")
    p.add_argument("--root", type=Path, default=Path.cwd())
    p.add_argument("--lang", default="en")
    p.add_argument("--out", type=Path, default=None,
                   help="output manifest path (default: <root>/.claude/pack.manifest.yaml)")
    p.add_argument("--force", action="store_true")
    p.add_argument("--allow-dev-version", action="store_true")
    args = p.parse_args(argv)

    root = args.root.resolve()
    out_path = args.out or (root / ".claude" / "pack.manifest.yaml")

    if args.discover:
        json.dump(discover(root), sys.stdout, indent=2)
        sys.stdout.write("\n")
        return EXIT_OK

    if args.list_questions:
        d = discover(root)
        json.dump(list_questions(d, args.lang), sys.stdout, indent=2)
        sys.stdout.write("\n")
        return EXIT_OK

    if args.write:
        try:
            answers = json.loads(sys.stdin.read() or "{}")
        except json.JSONDecodeError as e:
            sys.stderr.write(f"answers JSON parse error: {e}\n")
            return EXIT_VALIDATION
        if not isinstance(answers, dict):
            sys.stderr.write(
                f"answers JSON must be an object (dict); got {type(answers).__name__}\n"
            )
            return EXIT_VALIDATION
        return write_manifest(answers, out_path, root,
                              force=args.force,
                              allow_dev_version=args.allow_dev_version)

    return EXIT_VALIDATION


if __name__ == "__main__":
    sys.exit(main())
